name: run-tests

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/run-tests.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.4, 8.3]
        stability: [prefer-lowest, prefer-stable]
        include:
          # Laravel 12 configuration
          - laravel: 12.*
            testbench: 10.*
            pest: 2.*
            phpunit: ^11.0
            collision: ^8.1
            php: 8.4

          # Laravel 11 configuration
          - laravel: 11.*
            testbench: 9.*
            pest: 2.*
            phpunit: ^10.5
            collision: ^7.0
            php: 8.3

          # Laravel 10 configuration
          - laravel: 10.*
            testbench: 8.*
            pest: 2.*
            phpunit: ^10.0
            collision: ^7.0
            php: 8.3

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Temporarily modify composer.json
        run: |
          # Create a temporary composer.json that will be used just for this test run
          # This prevents permanent modifications to the actual composer.json file
          cp composer.json composer.json.bak

          # Update dependencies to match matrix requirements
          composer config --no-plugins --no-scripts require-dev.phpunit/phpunit "${{ matrix.phpunit }}"
          composer config --no-plugins --no-scripts require-dev.pestphp/pest "${{ matrix.pest }}"
          composer config --no-plugins --no-scripts require-dev.nunomaduro/collision "${{ matrix.collision }}"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest --ci

      - name: Restore composer.json
        if: always()
        run: mv composer.json.bak composer.json
